### ISSUE TITLE
How to download a smpl_model in the same format as your requirements?

### ISSUE THREAD

**Issue by fuqifan** [kakaobrain/flame#11]
Hi, thank you for your brilliant work! 

I could not find the smpl_model in the required format at AMASS. The SMPL_python_v.1.1.0 models I found on the AMASS website that are compatible with python have the following format: 
smpl/
├── models
│   └── basicmodel_f_lbs_10_207_0_v1.1.0.pkl
│   └── basicmodel_m_lbs_10_207_0_v1.1.0.pkl
│   └── basicmodel_neutral_lbs_10_207_0_v1.1.0.pkl
├── .DS_Store
├── __init__.py
└── smpl_webuser
    └── hello_world
        └── hello_smpl.py
        └── render_smpl.py
    └── lbs.py
    └── LICENSE.txt
    └── posemapper.py
    └── README.txt
    └── serialization.py
    └── verts.py

Could you please tell me how to get the smpl_model in the format requested below?
smpl_model/
├── female
│   └── model.npz
├── info.txt
├── LICENSE.txt
├── male
│   └── model.npz
└── neutral
    └── model.npz

Thank you in advance!

**Comment by jihoonerd** [comment]
You can get the corresponding SMPL+H files from the official guide from [AMASS](https://github.com/nghorbani/amass).
